name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
           login-server: containerregistrynameoctaviandragusanu30643.azurecr.io
           username: containerregistrynameoctaviandragusanu30643
           password: L2EWdkh1dwQYDoH5L=xu49LDTD0WKwwB
      - run: |
          docker build . -t containerregistrynameoctaviandragusanu30643.azurecr.io /proiectsd:${{ github.sha }}
          docker push containerregistrynameoctaviandragusanu30643.azurecr.io /proiectsd:${{ github.sha }}
