name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: containerregistrynameoctaviandragusanu30643.azurecr.io
          username: ${{ ACR.ACR_USERNAME }}
          password: ${{ ACR.ACR_PASSWORD }}

      - run: |
          docker build . -t containerregistrynameoctaviandragusanu30643.azurecr.io/appdb:${{ github.sha }}
          docker push containerregistrynameoctaviandragusanu30643.azurecr.io/appdb:${{ github.sha }}
